services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  minio:
    image: quay.io/minio/minio:latest
    container_name: footballdataplatform-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  crawlers:
    build:
      context: .
      dockerfile: crawlers/Dockerfile
    container_name: footballdataplatform-crawlers
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    working_dir: /app
    init: true
    shm_size: "1gb"
    profiles:
      - tools # không tự khởi động khi "docker compose up"
  
  ingestion:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    container_name: footballdataplatform-ingestion-1
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/football
      RAW_DATA_DIR: /app/data/raw
    volumes:
      - ./data/raw:/app/data/raw:ro
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - tools   # không tự khởi động khi "docker compose up"

volumes:
  pgdata:
  minio_data: